jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.application.name=servico-usuario
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.instance.prefer-ip-address=true
server.port=0

eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${JAEGER_URL}
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]