spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.application.name=servico-usuario
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.instance.prefer-ip-address=true
server.port=0