apiVersion: v1
kind: Secret
metadata:
  name: batch-env
type: Opaque
stringData:
  DB_URL: "r2dbc:mysql://mysql:3306/reservas_servico_reserva"
  DATASOURCE_URL: "jdbc:mysql://mysql:3306/reservas_servico_reserva"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  EUREKA_URL: "http://ms-server:8080/eureka"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  KAFKA_URL: kafka-broker:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: email-env
type: Opaque
stringData:
  EUREKA_URL: http://ms-server:8080/eureka
  EMAIL_USERNAME: gertuy9@gmail.com
  EMAIL_PASSWORD_VOLLMED: lmsp jmqt oplh izme
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-env
type: Opaque
stringData:
  EUREKA_URL: http://ms-server:8080/eureka
---
apiVersion: v1
kind: Secret
metadata:
  name: log-env
type: Opaque
stringData:
  EUREKA_URL: http://ms-server:8080/eureka
  KAFKA_URL: kafka-broker:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: reserva-env
type: Opaque
stringData:
  DB_URL: r2dbc:mysql://mysql:3306/reservas_servico_reserva
  DB_URL_FLYWAY: jdbc:mysql://mysql:3306/reservas_servico_reserva
  DB_USERNAME: root
  DB_PASSWORD: root
  MS_SALA_URL: http://servico-sala
  MS_USUARIO_URL: http://servico-usuario
  EUREKA_URL: http://ms-server:8080/eureka
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  KAFKA_URL: kafka-broker:29092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JAEGER_URL: http://jaeger:4318/v1/traces
---
apiVersion: v1
kind: Secret
metadata:
  name: sala-env
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql:3306/reservas_servico_sala?createDatabaseIfNotExist=true
  DB_USERNAME: root
  DB_PASSWORD: root
  EUREKA_URL: http://ms-server:8080/eureka
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JAEGER_URL: http://jaeger:4318/v1/traces
---
apiVersion: v1
kind: Secret
metadata:
  name: sugestoes-env
type: Opaque
stringData:
  MS_RESERVAS: http://gateway:8081/servico-reserva/
  MS_SALAS: http://gateway:8081/servico-sala/
  KAFKA_URL: kafka-broker:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: usuario-env
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql:3306/reservas_servico_usuario?createDatabaseIfNotExist=true
  DB_USERNAME: root
  DB_PASSWORD: root
  EUREKA_URL: http://ms-server:8080/eureka
  JAEGER_URL: http://jaeger:4318/v1/traces
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-env
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: reservas_servico_reserva 
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-env
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest