quarkus.http.port=8085

quarkus.rest-client.ms-reservas.url=${MS_RESERVAS}
quarkus.rest-client.ms-salas.url=${MS_SALAS}

mp.messaging.outgoing.sugestoes.connector=smallrye-kafka
mp.messaging.outgoing.sugestoes.topic=sugestao-aceita
mp.messaging.outgoing.sugestoes.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.sugestoes.bootstrap.servers=${KAFKA_URL}