spring.application.name=servico_email
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=0

spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD_VOLLMED}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
logging.level.org.springframework.amqp=DEBUG