spring.application.name=servico-batch
spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.datasource.jdbc-url=${DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG

eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.instance.prefer-ip-address=true
server.port=0

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_URL}