spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.flyway.url=${DB_URL_FLYWAY}
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}

servico.sala.base-url=${MS_SALA_URL}
servico.usuario.base-url=${MS_USUARIO_URL}

spring.application.name=servico-reserva
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.instance.prefer-ip-address=true
server.port=0

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_URL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.repositories.enabled=false

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${JAEGER_URL}
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]